version: "3"

services: 
  valheim: 
    image: ghcr.io/lloesche/valheim-server
    cap_add:
      - sys_nice
    volumes: 
      - valheim-data:/config
      - valheim-data:/opt/valheim
    ports: 
      - "2456-2458:2456-2458/udp"
      - "9001:9001/tcp"
    env_file:
      - $HOME/valheim-server/valheim.env
    restart: always
    stop_grace_period: 2m
volumes:
  valheim-data:
      driver: local
      driver_opts:
        type: nfs
        o: addr=192.168.1.X,rw
        device: ":/mnt/<NFS SHARE PATH>/valheim"
